---
- name: MAJ Update OS
  hosts: linux   #(ou mettre son titre de groupe présent dans le fichier inventaire.ini)
  become: yes
  tasks:
    - name: MAJ paquet-list
      apt:
        update_cache: yes

    - name: MAJ Upgrade paquet
      apt:
        upgrade: dist


