---

- name: Test Connectivity and Gather Facts on Windows Host
  hosts: windows
  gather_facts: no

  tasks:
  - name: Test WinRM Connectivity
    win_ping:

  - name: Gather Windows Facts
    setup:

  - name: Display Some Windows Facts
    debug:
      msg:
      - "Operating System: {{ ansible_os_name }}"
      - "Total RAM: {{ ansible_memtotal_mb }} MB"
      - "Processor: {{ ansible_processor[0] }}"
