---

- name: Créer un utilisateur Active Directory
  hosts: windows_servers  
  gather_facts: no

  tasks:
    - name: Ajouter un utilisateur à Active Directory
      win_domain_user:
        name: "{{ ad_username }}"
        password: "{{ ad_user_password }}"
        state: present
        domain_username: "{{ ad_admin_username }}"
        domain_password: "{{ ad_admin_password }}"
        domain_server: "{{ ad_domain_controller }}"
        groups:
          - "Users"  
      become: no

      vars:
        ad_username: "Allan Foirey"  
        ad_user_password: "CunTest1205@"  
        ad_admin_username: "Administrateur"  
        ad_admin_password: "Jsa100pc@"  
        ad_domain_controller: "10.0.2.50"  

