---

- name: AD-usze
  hosts: windows_servers
  gather_facts: no
  tasks:
    - name: NEw user
      win_domain_user:
        name: "GLyonremi"
        firstname: "remi"
        surname: "dupont"
        password: "Jsa100pc@"
        state: present
        path: "OU=Users,DC=ansible,DC=awx" 
        groups:
          - "AWX_Required_GROUP"
        upn: "rduminy@grandlyon.com"
        must_change_password: no
        password_never_expires: yes
      delegate_to: localhost

