---

- name: Créer un utilisateur sur Windows
  hosts: windows
  gather_facts: no
  tasks:
    - name: Créer un utilisateur
      win_user:
        name: Allan Fe
        password: MotDePasse@123
        state: present
      become: yes
      become_user: "{{ ansible_user }}"
      become_method: runas

